name: Warehouse Management System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - id: build
        name: Build
        run: mvn clean compile

      - id: test
        name: Test
        if: steps.build.outcome == 'success'
        run: mvn test